Repository uriparser/uriparser, pull requests merged in 2021-03, with the labels that each got.

#100 CMakeLists.txt: Link against pthreads for -DURIPARSER_BUILD_TESTS=ON (fixes #99)
  CMakeLists.txt
  ChangeLog
Labels: bug, compilation

#101 Migrate from Travis Ci to GitHub Actions
  .github/dependabot.yml
  .github/workflows/build-and-test.yml
  .travis.yml
Labels: enhancement

#102 CMake: Introducs build flag that turns warnings into errors
  .github/workflows/build-and-test.yml
  CMakeLists.txt
  ChangeLog
  README.md
  appveyor.yml
Labels: enhancement

#98 Add CMAKE_CURRENT_SOURCE_DIR prefix to sources
  CMakeLists.txt
Labels: bug, compilation

#104 Stop misadvertising wide strings as Unicode support
  ChangeLog
  README.md
  doc/Mainpage.txt
  include/uriparser/UriDefsConfig.h
  include/uriparser/UriDefsUnicode.h
  test/test.cpp
Labels: bug, documentation

#103 CMake: Improve qhelpgenerator auto-detection
  CMakeLists.txt
  ChangeLog
  README.md
  THANKS
Labels: enhancement

#106 docs: Use pkg-config for detection in configure.ac (fixes #37)
  ChangeLog
  doc/Mainpage.txt
Labels: documentation, enhancement

#108 Prepare release 0.9.5
  CMakeLists.txt
  ChangeLog
  include/uriparser/Uri.h
  include/uriparser/UriBase.h
Labels: releasing

#111 Address MSVC compiler warnings
  CMakeLists.txt
  ChangeLog
Labels: enhancement, windows

#110 CMake: Only set CMAKE_CXX_FLAGS after enable_language(CXX)
  CMakeLists.txt
  ChangeLog
  THANKS
  appveyor.yml
Labels: bug, compilation

#112 AppVeyor: Add MSVC 2019
  appveyor.yml
Labels: compilation, enhancement, windows

#113 Address MSVC compiler warnings
  CMakeLists.txt
  ChangeLog
  test/MemoryManagerSuite.cpp
Labels: compilation, enhancement
