Repository uriparser/uriparser, pull requests merged in 2022-10, with the labels that each got.

#150 Fix IPv6 and IPvFuture literal parsing
  src/UriParse.c
  test/test.cpp
Labels: bug

#152 CI: Add MSVC 17/2022
  appveyor.yml
Labels: enhancement

#154 Prepare release 0.9.7 (part of #153)
  CMakeLists.txt
  ChangeLog
  THANKS
  include/uriparser/Uri.h
  include/uriparser/UriBase.h
Labels: releasing
