Repository uriparser/uriparser, pull requests merged in 2022-01, with the labels that each got.

#129 Release uriparser 0.9.6 (part of #128)
  CMakeLists.txt
  ChangeLog
  include/uriparser/Uri.h
  include/uriparser/UriBase.h
Labels: security, releasing

#130 Actions: Upgrade Clang from 11 to 13
  .github/workflows/build-and-test.yml
Labels: enhancement

#131 uriparse: use size_t for inet_ntop declaration and fix macro checks for MinGW and mingw-w64
  tool/uriparse.c
Labels: windows, compilation

#136 UriMemory.c: Add comment on need for config.h
  src/UriMemory.c
Labels: enhancement
